version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "npm run start"